In [8]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ram", "Shyam", "Hari", "Sita", "Gita",
        "Nabin", "Rita", "Bikash", "Anita", "Suman"
    ],

    # Categorical variables
    "Gender": [
        "Male", "Male", np.nan, "Female", "Female",
        "Male", "Female", "Male", "Female", "Male"
    ],  # 10% missing

    "City": [
        "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Kathmandu",
        "Pokhara", "Lalitpur", "Kathmandu", "Pokhara", np.nan
    ],  # 10% missing

    "Department": [
        "IT", np.nan, np.nan, "Finance", "IT",
        np.nan, "HR", np.nan, "IT", "Finance"
    ],  # 40% missing

    # Numerical variables
    "Age": [
        20, 22, np.nan, 21, 23,
        24, 25, 26, 22, 21
    ],  # 10% missing

    "Math": [
        80, 75, 90, np.nan, 85,
        78, 88, 92, 70, 95
    ],  # 10% missing

    "Salary": [
        30000, np.nan, np.nan, 40000, np.nan,
        35000, np.nan, 50000, np.nan, 38000
    ]  # 50% missing 
})
df

     Name  Gender       City Department   Age  Math   Salary
0     Ram    Male  Kathmandu         IT  20.0  80.0  30000.0
1   Shyam    Male    Pokhara        NaN  22.0  75.0      NaN
2    Hari     NaN   Lalitpur        NaN   NaN  90.0      NaN
3    Sita  Female  Bhaktapur    Finance  21.0   NaN  40000.0
4    Gita  Female  Kathmandu         IT  23.0  85.0      NaN
5   Nabin    Male    Pokhara        NaN  24.0  78.0  35000.0
6    Rita  Female   Lalitpur         HR  25.0  88.0      NaN
7  Bikash    Male  Kathmandu        NaN  26.0  92.0  50000.0
8   Anita  Female    Pokhara         IT  22.0  70.0      NaN
9   Suman    Male        NaN    Finance  21.0  95.0  38000.0

In [9]:
#drop column which has less than 80% of data:

thresh_data = int(len(df) * 0.8)
df.dropna(axis=1, thresh= thresh_data)

     Name  Gender       City   Age  Math
0     Ram    Male  Kathmandu  20.0  80.0
1   Shyam    Male    Pokhara  22.0  75.0
2    Hari     NaN   Lalitpur   NaN  90.0
3    Sita  Female  Bhaktapur  21.0   NaN
4    Gita  Female  Kathmandu  23.0  85.0
5   Nabin    Male    Pokhara  24.0  78.0
6    Rita  Female   Lalitpur  25.0  88.0
7  Bikash    Male  Kathmandu  26.0  92.0
8   Anita  Female    Pokhara  22.0  70.0
9   Suman    Male        NaN  21.0  95.0