In [178]:
#before diving first learn train_test_split.png image  

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ram", "Shyam", "Hari", "Sita", "Gita",
        "Nabin", "Rita", "Bikash", "Anita", "Suman"
    ],

    # Categorical variables
    "Gender": [
        "Male", "Male", np.nan, "Female", "Female",
        "Male", "Female", "Male", "Female", "Male"
    ],  # 10% missing

    "City": [
        "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Kathmandu",
        "Pokhara", "Lalitpur", "Kathmandu", "Pokhara", np.nan
    ],  # 10% missing

    "Department": [
        "IT", np.nan, np.nan, "Finance", "IT",
        np.nan, "HR", np.nan, "IT", "Finance"
    ],  # 40% missing

    # Numerical variables
    "Age": [
        20, 22, np.nan, 21, 23,
        24, 25, 26, 22, 21
    ],  # 10% missing

    "Math": [
        80, 75, 90, np.nan, 85,
        78, 88, 92, 70, 95
    ],  # 10% missing

    "Salary": [
        30000, np.nan, np.nan, 40000, np.nan,
        35000, np.nan, 50000, np.nan, 38000
    ]  # 50% missing 
})

df

     Name  Gender       City Department   Age  Math   Salary
0     Ram    Male  Kathmandu         IT  20.0  80.0  30000.0
1   Shyam    Male    Pokhara        NaN  22.0  75.0      NaN
2    Hari     NaN   Lalitpur        NaN   NaN  90.0      NaN
3    Sita  Female  Bhaktapur    Finance  21.0   NaN  40000.0
4    Gita  Female  Kathmandu         IT  23.0  85.0      NaN
5   Nabin    Male    Pokhara        NaN  24.0  78.0  35000.0
6    Rita  Female   Lalitpur         HR  25.0  88.0      NaN
7  Bikash    Male  Kathmandu        NaN  26.0  92.0  50000.0
8   Anita  Female    Pokhara         IT  22.0  70.0      NaN
9   Suman    Male        NaN    Finance  21.0  95.0  38000.0

In [179]:
df.isna().sum()

Name          0
Gender        1
City          1
Department    4
Age           1
Math          1
Salary        5
dtype: int64

In [180]:
df_numerical = df.select_dtypes(include = ['int64','float64'])

In [181]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = "mean")
df_numerical_imputed = imputer.fit_transform(df_numerical)
df_numerical_imputed.round(1)

array([[2.00e+01, 8.00e+01, 3.00e+04],
       [2.20e+01, 7.50e+01, 3.86e+04],
       [2.27e+01, 9.00e+01, 3.86e+04],
       [2.10e+01, 8.37e+01, 4.00e+04],
       [2.30e+01, 8.50e+01, 3.86e+04],
       [2.40e+01, 7.80e+01, 3.50e+04],
       [2.50e+01, 8.80e+01, 3.86e+04],
       [2.60e+01, 9.20e+01, 5.00e+04],
       [2.20e+01, 7.00e+01, 3.86e+04],
       [2.10e+01, 9.50e+01, 3.80e+04]])

In [182]:
df[imputer.get_feature_names_out()] = df_numerical_imputed #It gives columns names
df

     Name  Gender       City Department        Age       Math   Salary
0     Ram    Male  Kathmandu         IT  20.000000  80.000000  30000.0
1   Shyam    Male    Pokhara        NaN  22.000000  75.000000  38600.0
2    Hari     NaN   Lalitpur        NaN  22.666667  90.000000  38600.0
3    Sita  Female  Bhaktapur    Finance  21.000000  83.666667  40000.0
4    Gita  Female  Kathmandu         IT  23.000000  85.000000  38600.0
5   Nabin    Male    Pokhara        NaN  24.000000  78.000000  35000.0
6    Rita  Female   Lalitpur         HR  25.000000  88.000000  38600.0
7  Bikash    Male  Kathmandu        NaN  26.000000  92.000000  50000.0
8   Anita  Female    Pokhara         IT  22.000000  70.000000  38600.0
9   Suman    Male        NaN    Finance  21.000000  95.000000  38000.0

In [183]:
test_df = pd.DataFrame({
    "Name": [
        "Aashish", "Kiran"
    ],

    "Gender": [
        "Male", np.nan
    ],

    "City": [
        "Pokhara", "Kathmandu"
    ],

    "Department": [
        np.nan, "Finance"
    ],

    "Age": [
        23, np.nan
    ],

    "Math": [
        88, 76
    ],

    "Salary": [
        np.nan, 42000
    ]
})
test_df

      Name Gender       City Department   Age  Math   Salary
0  Aashish   Male    Pokhara        NaN  23.0    88      NaN
1    Kiran    NaN  Kathmandu    Finance   NaN    76  42000.0

In [184]:
#get mean from train data and fill test data 

df_numerical_test = test_df.select_dtypes(include=['int64','float64'])

df_numerical_test_imputed = imputer.transform(df_numerical_test)

test_df[imputer.get_feature_names_out()] = df_numerical_test_imputed
test_df

      Name Gender       City Department        Age  Math   Salary
0  Aashish   Male    Pokhara        NaN  23.000000  88.0  38600.0
1    Kiran    NaN  Kathmandu    Finance  22.666667  76.0  42000.0

In [185]:
#fill categorical value:
df_categorical = df.select_dtypes(include= "str")
imputer1 = SimpleImputer(strategy='most_frequent')
df_categorical_imputed = imputer1.fit_transform(df_categorical)
df[imputer1.get_feature_names_out()]= df_categorical_imputed
df

     Name  Gender       City Department        Age       Math   Salary
0     Ram    Male  Kathmandu         IT  20.000000  80.000000  30000.0
1   Shyam    Male    Pokhara         IT  22.000000  75.000000  38600.0
2    Hari    Male   Lalitpur         IT  22.666667  90.000000  38600.0
3    Sita  Female  Bhaktapur    Finance  21.000000  83.666667  40000.0
4    Gita  Female  Kathmandu         IT  23.000000  85.000000  38600.0
5   Nabin    Male    Pokhara         IT  24.000000  78.000000  35000.0
6    Rita  Female   Lalitpur         HR  25.000000  88.000000  38600.0
7  Bikash    Male  Kathmandu         IT  26.000000  92.000000  50000.0
8   Anita  Female    Pokhara         IT  22.000000  70.000000  38600.0
9   Suman    Male  Kathmandu    Finance  21.000000  95.000000  38000.0

In [186]:
#test_df:
test_df[imputer1.get_feature_names_out()] = imputer1.transform(test_df[imputer1.get_feature_names_out()])
test_df

      Name Gender       City Department        Age  Math   Salary
0  Aashish   Male    Pokhara         IT  23.000000  88.0  38600.0
1    Kiran   Male  Kathmandu    Finance  22.666667  76.0  42000.0