In [58]:
import pandas as pd

df = pd.DataFrame({
    "Study Hours": [2, 3, 4, 5, 6, 7, 1, 8],
    "Attendance": [60, 65, 70, 75, 80, 85, 50, 90],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Result": ["Fail", "Fail", "Pass", "Pass", "Pass", "Pass", "Fail", "Pass"]
})

print(df)

   Study Hours  Attendance  Gender Result
0            2          60    Male   Fail
1            3          65  Female   Fail
2            4          70    Male   Pass
3            5          75  Female   Pass
4            6          80    Male   Pass
5            7          85  Female   Pass
6            1          50    Male   Fail
7            8          90  Female   Pass

In [59]:
feature = ['Result']

In [60]:
from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()
encoded_feature = encoder.fit_transform(df[feature])

encoded_feature

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 1, 1, 1, 1, 0, 1])

In [61]:
df['Result']= encoded_feature
df

   Study Hours  Attendance  Gender  Result
0            2          60    Male       0
1            3          65  Female       0
2            4          70    Male       1
3            5          75  Female       1
4            6          80    Male       1
5            7          85  Female       1
6            1          50    Male       0
7            8          90  Female       1

In [62]:
from sklearn.preprocessing import OneHotEncoder

feature1 = ['Gender']

encoder1 = OneHotEncoder()
encoded_feature1 = encoder1.fit_transform(df[feature1])
encoded_feature1.toarray()

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [63]:
df[encoder1.get_feature_names_out()]= encoded_feature1.toarray()

df

   Study Hours  Attendance  Gender  Result  Gender_Female  Gender_Male
0            2          60    Male       0            0.0          1.0
1            3          65  Female       0            1.0          0.0
2            4          70    Male       1            0.0          1.0
3            5          75  Female       1            1.0          0.0
4            6          80    Male       1            0.0          1.0
5            7          85  Female       1            1.0          0.0
6            1          50    Male       0            0.0          1.0
7            8          90  Female       1            1.0          0.0

In [64]:
df.drop(columns= feature1,inplace= True)
df

   Study Hours  Attendance  Result  Gender_Female  Gender_Male
0            2          60       0            0.0          1.0
1            3          65       0            1.0          0.0
2            4          70       1            0.0          1.0
3            5          75       1            1.0          0.0
4            6          80       1            0.0          1.0
5            7          85       1            1.0          0.0
6            1          50       0            0.0          1.0
7            8          90       1            1.0          0.0