In [3]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85.2134, 90.67812, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)

df

    Name  Age Gender      Math  Science       City
0    Ram   20      M  85.21340       80  Kathmandu
1   Sita   21      F  90.67812       85    Pokhara
2   Hari   19      M  70.00000       75  Kathmandu
3   Gita   22      F  95.00000       90   Lalitpur
4  Nabin   20      M  60.00000       65  Bhaktapur
5   Asha   21      F  88.00000       95    Pokhara
6  Rohan   23      M  75.00000       70  Kathmandu
7   Mina   19      F  92.00000       89   Lalitpur

In [4]:
df[df["Math"] >= 80]

   Name  Age Gender      Math  Science       City
0   Ram   20      M  85.21340       80  Kathmandu
1  Sita   21      F  90.67812       85    Pokhara
3  Gita   22      F  95.00000       90   Lalitpur
5  Asha   21      F  88.00000       95    Pokhara
7  Mina   19      F  92.00000       89   Lalitpur

In [6]:
#Filter those students whose both marks >= 80 and is male
df[(df["Math"]>=80)&(df["Science"]>=80)&(df["Gender"]=="M")]

  Name  Age Gender     Math  Science       City
0  Ram   20      M  85.2134       80  Kathmandu

In [ ]:
#Filter those whose age is 20 or 22
df[(df["Age"] == 20) | (df["Age"] == 22)]

    Name  Age Gender     Math  Science       City
0    Ram   20      M  85.2134       80  Kathmandu
3   Gita   22      F  95.0000       90   Lalitpur
4  Nabin   20      M  60.0000       65  Bhaktapur

In [11]:
#Filter whose city is not kathmandu
df[~(df["City"]=="Kathmandu")]

    Name  Age Gender      Math  Science       City
1   Sita   21      F  90.67812       85    Pokhara
3   Gita   22      F  95.00000       90   Lalitpur
4  Nabin   20      M  60.00000       65  Bhaktapur
5   Asha   21      F  88.00000       95    Pokhara
7   Mina   19      F  92.00000       89   Lalitpur