In [1]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85.2134, 90.67812, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)

df

    Name  Age Gender      Math  Science       City
0    Ram   20      M  85.21340       80  Kathmandu
1   Sita   21      F  90.67812       85    Pokhara
2   Hari   19      M  70.00000       75  Kathmandu
3   Gita   22      F  95.00000       90   Lalitpur
4  Nabin   20      M  60.00000       65  Bhaktapur
5   Asha   21      F  88.00000       95    Pokhara
6  Rohan   23      M  75.00000       70  Kathmandu
7   Mina   19      F  92.00000       89   Lalitpur

In [ ]:
#Filter Numerical and Categorical data types:
df.select_dtypes(include=["str"])

    Name Gender       City
0    Ram      M  Kathmandu
1   Sita      F    Pokhara
2   Hari      M  Kathmandu
3   Gita      F   Lalitpur
4  Nabin      M  Bhaktapur
5   Asha      F    Pokhara
6  Rohan      M  Kathmandu
7   Mina      F   Lalitpur

In [5]:
df.select_dtypes(include = ["int64","float64"] )

   Age      Math  Science
0   20  85.21340       80
1   21  90.67812       85
2   19  70.00000       75
3   22  95.00000       90
4   20  60.00000       65
5   21  88.00000       95
6   23  75.00000       70
7   19  92.00000       89

In [10]:
df.select_dtypes(include=["str"]).columns

Index(['Name', 'Gender', 'City'], dtype='str')

In [9]:
df.select_dtypes(include=["int64","float64"]).columns

Index(['Age', 'Math', 'Science'], dtype='str')